### ISSUE TITLE
No transparent 

### ISSUE THREAD

**Issue by Nivirog** [Suel-ki/Beautify-Refabricated#11]
Well...
![image](https://github.com/Suel-ki/Beautify-Refabricated/assets/71185309/0e853495-8ac6-4a29-a13f-f3c00874cfc9)
![image](https://github.com/Suel-ki/Beautify-Refabricated/assets/71185309/00dffe86-b0af-4ccb-91f5-f55d4b4f8a4a)
![image](https://github.com/Suel-ki/Beautify-Refabricated/assets/71185309/3df9cfc7-f4b9-44cf-9ec9-696b476591c9)
![image](https://github.com/Suel-ki/Beautify-Refabricated/assets/71185309/00dec247-868e-4536-9c9f-a6713a72ddc0)
![image](https://github.com/Suel-ki/Beautify-Refabricated/assets/71185309/48f9c7d9-2dd4-45da-84b7-7f17bae7c965)

**Comment by Suel-ki** [comment]
Provide logs if possible
