### ISSUE TITLE
[BUG] Mipmap dropped - Lowers overall textures - Important - 1.20.1 Fabric

### ISSUE THREAD

**Issue by xR4YM0ND** [Suel-ki/Beautify-Refabricated#12]
`[Worker-ResourceReload-0/WARN]: Texture beautify:block/trellis_weeping_vines_hanging with size 20x16 limits mip level from 4 to 2`

Version: Fabric 1.20.1
Beautify: 1.0.0+1.20

**Comment by xR4YM0ND** [comment]
Just change the textures to 32x16 like so:
![trellis_vine_hanging](https://github.com/Suel-ki/Beautify-Refabricated/assets/97298005/042b8491-e15a-4c20-9a24-109debc31a6a)
![trellis_weeping_vines_hanging](https://github.com/Suel-ki/Beautify-Refabricated/assets/97298005/76e77f3c-5c86-4e03-ae55-0fe53421e1c1)
![trellis_lichen_hanging](https://github.com/Suel-ki/Beautify-Refabricated/assets/97298005/a85ee520-9f5e-4606-b628-7c3594ff857f)
![trellis_lilac_hanging](https://github.com/Suel-ki/Beautify-Refabricated/assets/97298005/5c966ada-be56-4533-b673-afe4e05ae2b2)
![trellis_peony_hanging](https://github.com/Suel-ki/Beautify-Refabricated/assets/97298005/0fd89a0a-8ee9-46f8-840e-933c7f097153)
![trellis_rose_hanging](https://github.com/Suel-ki/Beautify-Refabricated/assets/97298005/dfde5c1c-6b29-4b5e-a9b1-51441ee67713)
![trellis_sunflower_hanging](https://github.com/Suel-ki/Beautify-Refabricated/assets/97298005/fe8b4543-8277-4f29-9d27-6d9a450d1710)
![trellis_twisting_vines_hanging](https://github.com/Suel-ki/Beautify-Refabricated/assets/97298005/5a8c8c78-f914-43c7-8851-3217851f2d3d)

**Comment by Suel-ki** [comment]
Sorry for taking so long to see this,  thank you very much
