### ISSUE TITLE
[Request] Compatibility with Every Compat

### ISSUE THREAD

**Issue by Kallixer** [Suel-ki/Beautify-Refabricated#18]
I really like this mod and would love to see it be compatible with [Every Compat](https://modrinth.com/mod/every-compat) if possible.

I know this is a fork, so maybe this should be requested on the main mods page, but I use the fabric version som I'm going to put it here. (Thanks for porting!)

**Comment by Suel-ki** [comment]
Sorry for the late response.

I'm not planning compatibility with other mods now, but you can submit your suggestions in the [issues](https://github.com/MehVahdJukaar/WoodGood/issues) of [Every Compat](https://modrinth.com/mod/every-compat).

**Comment by Kallixer** [comment]
Okay, I will do that. Thanks for answering!
