### ISSUE TITLE
[Suggestion] Mod Wood Support

### ISSUE THREAD

**Issue by Fyoncle** [Suel-ki/Beautify-Refabricated#23]
Modded wood variants & support for blinds and stuff? IF NOT, then can we use modded woods to craft blinds but it will give us the default oak wood one, because not being able to craft blinds with modded wood is kinda annoying.

**Comment by Suel-ki** [comment]
Maybe later, because I suck at art.

**Comment by Fyoncle** [comment]
> Maybe later, because I suck at art.

It cant be that baaad, its just wood that need to be recolored lol

**Comment by Suel-ki** [comment]
> > Maybe later, because I suck at art.
> 
> It cant be that baaad, its just wood that need to be recolored lol

It's been included in the [Every Compat](https://github.com/MehVahdJukaar/WoodGood) [project](https://github.com/users/MehVahdJukaar/projects/1), and may be supported in the future, although it may be a long time.

**Comment by Suel-ki** [comment]
It is now supported by Every Compat in 2.5.27

**Comment by Fyoncle** [comment]
> It is now supported by Every Compat in 2.5.27

But- why every compat :c
