### ISSUE TITLE
No crafting recipes

### ISSUE THREAD

**Issue by jamisosoup** [Suel-ki/Beautify-Refabricated#27]
As the title says. All the items exist just fine in the creative menu and creative worlds. I cannot craft any of the mod's items in my survival worlds. I can see the items in JEI too but also cannot look to see the crafting recipes there either

**Comment by RKDeviancy** [comment]
Same issue for me. For context, im on the most recent 1.21 file on Modrinth

**Comment by xtreyreader** [comment]
Same for me, downloaded the file from Curseforge, 1.21

**Comment by jshipley** [comment]
It should be because of the datapack changes. Recipe results now use "id": "modname:item" instead of "item": "modname:item"

**Comment by jshipley** [comment]
The block loot data is also broken, also due to changes to the datapack format. I think that moving the mineable tags from "minecraft/tags/blocks" to "minecraft/tags/block" should mostly fix it.

**Comment by Suel-ki** [comment]
Sorry for the hasty update, didn't notice the datapack format change, version 1.2.1 should fix it.

**Comment by RKDeviancy** [comment]
Thank you for gettin the fix out <3
