### ISSUE TITLE
1.19.3 Fabric Crashes on Startup

### ISSUE THREAD

**Issue by Zykana** [Suel-ki/Beautify-Refabricated#3]
[crash-2023-01-18_11.58.25-client.txt](https://github.com/Suel-ki/Beautify-Refabricated/files/10448790/crash-2023-01-18_11.58.25-client.txt)

Minecraft crashes on startup due to errors from beautify.

**Comment by Zykana** [comment]
[crash-2023-01-20_16.21.02-client.txt](https://github.com/Suel-ki/Beautify-Refabricated/files/10470334/crash-2023-01-20_16.21.02-client.txt)

Updated version and it still crashes.

**Comment by Suel-ki** [comment]
Clashed with the Lanterns Belong on Walls mod

**Comment by BeeFox-sys** [comment]
Confirming crash in conjunction with Lanterns Belong On Walls
